CREATE DATABASE YATSENKO_3;

CREATE TABLE EMPLOYEES (
    id INTEGER PRIMARY KEY,
    Job_Title VARCHAR

);

INSERT INTO EMPLOYEES VALUES (1, 'Developer);
INSERT INTO EMPLOYEES VALUES (2, 'Developer');

SELECT * FROM EMPLOYEES;